export const careersSeed = [
  {
    title: "Senior Travel Consultant — Dubai & Middle East",
    department: "operations",
    location: "Bengaluru",
    type: "full-time",
    experience: "3–5 years",
    description: "Lead our Dubai and Middle East travel vertical. You'll craft luxury itineraries, manage key supplier relationships, and mentor junior consultants.",
    requirements: ["3+ years in travel/tourism industry", "Deep knowledge of Dubai, Abu Dhabi, Oman", "Excellent communication skills", "Experience with B2C luxury travel"],
    responsibilities: ["Design and optimize Dubai/ME itineraries", "Manage relationships with hotels and DMCs", "Handle VIP and high-value bookings", "Train and mentor junior consultants"],
    benefits: ["Annual travel allowance ₹50,000", "Health insurance for family", "Performance bonuses", "Flexible work hours"],
    salary: { min: 600000, max: 1000000, currency: "INR" },
    isActive: true,
  },
  {
    title: "Customer Experience Manager",
    department: "operations",
    location: "Mumbai",
    type: "full-time",
    experience: "2–4 years",
    description: "Own the end-to-end customer journey from booking to post-trip. Ensure every traveller has a seamless, delightful experience.",
    requirements: ["2+ years in customer success/experience", "Strong problem-solving skills", "Experience with CRM tools", "Empathetic communication style"],
    responsibilities: ["Manage customer communications pre/during/post trip", "Resolve escalations within SLA", "Gather and act on customer feedback", "Improve NPS and satisfaction scores"],
    benefits: ["Health insurance", "Learning budget ₹30,000/year", "Work from home 2 days/week"],
    salary: { min: 500000, max: 800000, currency: "INR" },
    isActive: true,
  },
  {
    title: "Destination Expert — Southeast Asia",
    department: "operations",
    location: "Remote",
    type: "full-time",
    experience: "1–3 years",
    description: "Become our go-to expert for Thailand, Bali, Singapore, and Vietnam. Research, travel, and create unforgettable itineraries.",
    requirements: ["Travelled extensively in SE Asia", "1+ year in travel planning", "Strong writing skills", "Detail-oriented"],
    responsibilities: ["Research and curate SE Asia packages", "Visit destinations quarterly for quality checks", "Write destination guides and content", "Support sales team with expertise"],
    benefits: ["Quarterly destination visits (paid)", "Remote-first role", "Annual travel allowance"],
    salary: { min: 400000, max: 700000, currency: "INR" },
    isActive: true,
  },
  {
    title: "Performance Marketing Lead — Paid Social & Search",
    department: "marketing",
    location: "Bengaluru",
    type: "full-time",
    experience: "4–6 years",
    description: "Scale our paid acquisition channels. Own Google Ads, Meta Ads, and emerging platforms to drive qualified leads at target CAC.",
    requirements: ["4+ years managing paid media budgets >₹50L/month", "Google Ads & Meta certified", "Strong analytical skills", "Experience in travel/e-commerce preferred"],
    responsibilities: ["Plan and execute paid campaigns across channels", "Optimize for CAC, ROAS, and LTV", "A/B test creatives and landing pages", "Report weekly to leadership"],
    benefits: ["Competitive salary + performance bonus", "MacBook Pro provided", "Health insurance", "Flexible hours"],
    salary: { min: 1200000, max: 1800000, currency: "INR" },
    isActive: true,
  },
  {
    title: "Content Strategist & Travel Writer",
    department: "marketing",
    location: "Remote",
    type: "full-time",
    experience: "2–4 years",
    description: "Create compelling travel content that inspires and converts. From blog posts to social captions to email campaigns.",
    requirements: ["2+ years content writing (travel preferred)", "SEO knowledge", "Portfolio of published work", "Can write 3000+ words/day"],
    responsibilities: ["Write blog posts, guides, and landing pages", "Develop content calendar", "Optimize existing content for SEO", "Collaborate with design team on visuals"],
    benefits: ["Remote-first", "Travel allowance for research trips", "Learning budget", "Flexible schedule"],
    salary: { min: 500000, max: 900000, currency: "INR" },
    isActive: true,
  },
  {
    title: "Social Media & Video Creator",
    department: "marketing",
    location: "Bengaluru",
    type: "full-time",
    experience: "1–3 years",
    description: "Create scroll-stopping reels, stories, and video content that showcases our destinations and grows our social following.",
    requirements: ["1+ year creating social content", "Proficient in Premiere Pro/CapCut", "Strong visual eye", "Understanding of Instagram/YouTube algorithms"],
    responsibilities: ["Create 15+ reels/month", "Manage Instagram and YouTube content", "Edit travel footage from our trips", "Grow followers and engagement"],
    benefits: ["Travel with the team for content shoots", "Latest equipment provided", "Creative freedom"],
    salary: { min: 400000, max: 700000, currency: "INR" },
    isActive: true,
  },
  {
    title: "Senior Full-Stack Engineer (React + Node)",
    department: "technology",
    location: "Remote",
    type: "full-time",
    experience: "4–7 years",
    description: "Build and scale our travel platform. Work on the booking engine, recommendation system, and customer-facing features.",
    requirements: ["4+ years with React/Next.js + Node.js", "MongoDB/PostgreSQL experience", "TypeScript proficiency", "System design knowledge"],
    responsibilities: ["Build new features for the booking platform", "Optimize performance and scalability", "Code review and mentor juniors", "Participate in architecture decisions"],
    benefits: ["Remote-first", "MacBook Pro + monitor", "ESOPs for senior roles", "Conference budget"],
    salary: { min: 2000000, max: 3500000, currency: "INR" },
    isActive: true,
  },
  {
    title: "Product Designer — UX/UI (Travel Platform)",
    department: "technology",
    location: "Bengaluru",
    type: "full-time",
    experience: "3–5 years",
    description: "Design beautiful, intuitive experiences for our travel platform. From search to booking to post-trip — every pixel matters.",
    requirements: ["3+ years product design experience", "Figma expert", "Portfolio showing end-to-end product work", "User research experience"],
    responsibilities: ["Design new features end-to-end", "Conduct user research and testing", "Maintain design system", "Collaborate with engineering on implementation"],
    benefits: ["Latest MacBook + 4K display", "Design conference budget", "Flexible hours", "Health insurance"],
    salary: { min: 1500000, max: 2500000, currency: "INR" },
    isActive: true,
  },
  {
    title: "Data Analyst — Growth & Revenue",
    department: "technology",
    location: "Remote",
    type: "full-time",
    experience: "2–4 years",
    description: "Turn data into insights that drive growth. Analyze booking patterns, customer behavior, and revenue metrics to inform strategy.",
    requirements: ["2+ years data analysis", "SQL + Python/R proficiency", "Experience with BI tools (Metabase/Looker)", "Statistical thinking"],
    responsibilities: ["Build dashboards for key metrics", "Analyze conversion funnels", "Identify growth opportunities from data", "Support marketing with attribution analysis"],
    benefits: ["Remote-first", "Learning budget", "Health insurance", "Performance bonus"],
    salary: { min: 800000, max: 1400000, currency: "INR" },
    isActive: true,
  },
  {
    title: "Talent Acquisition Specialist",
    department: "hr",
    location: "Bengaluru",
    type: "full-time",
    experience: "2–4 years",
    description: "Find and attract exceptional talent to join our growing team. Own the full recruitment lifecycle from sourcing to offer.",
    requirements: ["2+ years in recruitment", "Experience hiring for tech + non-tech roles", "Strong sourcing skills (LinkedIn, etc.)", "Excellent interpersonal skills"],
    responsibilities: ["Source and screen candidates", "Manage interview process end-to-end", "Build employer brand on LinkedIn", "Improve hiring metrics (time-to-hire, quality)"],
    benefits: ["Health insurance", "Learning budget", "Team events", "Flexible hours"],
    salary: { min: 500000, max: 900000, currency: "INR" },
    isActive: true,
  },
  {
    title: "Finance Manager — Revenue & Reconciliation",
    department: "finance",
    location: "Bengaluru",
    type: "full-time",
    experience: "5–8 years",
    description: "Manage financial operations including revenue recognition, vendor payments, reconciliation, and financial reporting.",
    requirements: ["CA/CMA or MBA Finance", "5+ years in finance operations", "Experience with travel/e-commerce", "Advanced Excel + Tally/SAP"],
    responsibilities: ["Manage daily revenue reconciliation", "Handle vendor payments and contracts", "Prepare monthly financial reports", "Ensure compliance with tax regulations"],
    benefits: ["Competitive salary", "Health insurance for family", "Annual bonus", "Professional development budget"],
    salary: { min: 1200000, max: 2000000, currency: "INR" },
    isActive: true,
  },
];
