export const destinationsSeed = [
  {
    name: 'Dubai',
    slug: 'dubai',
    country: 'UAE',
    region: 'Middle East',
    description: 'The city of gold — iconic skylines, desert safaris, and world-class luxury await in this dazzling metropolis.',
    shortDescription: 'Iconic skylines, desert safaris, and world-class luxury.',
    images: [
      'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80',
    ],
    category: 'city' as const,
    rating: 4.9,
    reviewCount: 312,
    packageCount: 48,
    startingPrice: 124999,
    bestSeason: 'Year-round',
    visaType: 'on-arrival' as const,
    highlights: ['Burj Khalifa', 'Desert Safari', 'Dubai Mall', 'Palm Jumeirah', 'Dhow Cruise'],
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Maldives',
    slug: 'maldives',
    country: 'Maldives',
    region: 'South Asia',
    description: 'A tropical paradise with pristine beaches, crystal-clear lagoons, and overwater bungalows like nowhere else on earth.',
    shortDescription: 'Pristine beaches, crystal-clear lagoons, and overwater bungalows.',
    images: [
      'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80',
    ],
    category: 'beach' as const,
    rating: 5.0,
    reviewCount: 209,
    packageCount: 31,
    startingPrice: 69999,
    bestSeason: 'Nov – Apr',
    visaType: 'on-arrival' as const,
    highlights: ['Overwater Villas', 'Snorkeling', 'Sunset Cruises', 'Underwater Dining', 'Spa Retreats'],
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Bali',
    slug: 'bali',
    country: 'Indonesia',
    region: 'Southeast Asia',
    description: 'An enchanting island offering stunning beaches, vibrant culture, lush rice terraces, and world-class wellness retreats.',
    shortDescription: 'Stunning beaches, vibrant culture, and wellness retreats.',
    images: [
      'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80',
    ],
    category: 'tropical' as const,
    rating: 4.9,
    reviewCount: 524,
    packageCount: 52,
    startingPrice: 44999,
    bestSeason: 'Apr – Oct',
    visaType: 'on-arrival' as const,
    highlights: ['Ubud Rice Terraces', 'Tanah Lot Temple', 'Seminyak Beach', 'Mount Batur', 'Spa & Wellness'],
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Japan',
    slug: 'japan',
    country: 'Japan',
    region: 'East Asia',
    description: 'Ancient temples, neon-lit cities, cherry blossoms, and bullet trains — Japan is a seamless blend of old and new.',
    shortDescription: 'Ancient temples, neon cities, and cherry blossoms.',
    images: [
      'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80',
    ],
    category: 'cultural' as const,
    rating: 4.9,
    reviewCount: 178,
    packageCount: 29,
    startingPrice: 114999,
    bestSeason: 'Mar – May',
    visaType: 'required' as const,
    highlights: ['Cherry Blossoms', 'Mount Fuji', 'Tokyo Shibuya', 'Kyoto Temples', 'Bullet Trains'],
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Singapore',
    slug: 'singapore',
    country: 'Singapore',
    region: 'Southeast Asia',
    description: 'A futuristic city-state where gleaming skyscrapers meet lush gardens, world-class food, and vibrant culture.',
    shortDescription: 'Futuristic city-state with gardens and world-class food.',
    images: [
      'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80',
    ],
    category: 'city' as const,
    rating: 4.8,
    reviewCount: 401,
    packageCount: 36,
    startingPrice: 72999,
    bestSeason: 'Year-round',
    visaType: 'free' as const,
    highlights: ['Marina Bay Sands', 'Gardens by the Bay', 'Sentosa Island', 'Universal Studios', 'Hawker Food'],
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Thailand',
    slug: 'thailand',
    country: 'Thailand',
    region: 'Southeast Asia',
    description: 'Turquoise waters, golden temples, vibrant street food, and island-hopping adventures across Phuket and Koh Samui.',
    shortDescription: 'Golden temples, turquoise waters, and vibrant street food.',
    images: [
      'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&q=80',
    ],
    category: 'beach' as const,
    rating: 4.8,
    reviewCount: 374,
    packageCount: 44,
    startingPrice: 39999,
    bestSeason: 'Nov – Apr',
    visaType: 'on-arrival' as const,
    highlights: ['Phi Phi Islands', 'Grand Palace', 'Floating Markets', 'Phuket Beaches', 'Thai Street Food'],
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Paris',
    slug: 'paris',
    country: 'France',
    region: 'Europe',
    description: 'The City of Light — iconic landmarks, world-class cuisine, romantic boulevards, and timeless art at every corner.',
    shortDescription: 'Iconic landmarks, world-class cuisine, and romantic boulevards.',
    images: [
      'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80',
    ],
    category: 'cultural' as const,
    rating: 4.8,
    reviewCount: 289,
    packageCount: 22,
    startingPrice: 149999,
    bestSeason: 'Apr – Jun',
    visaType: 'required' as const,
    highlights: ['Eiffel Tower', 'Louvre Museum', 'Champs-Élysées', 'Montmartre', 'Seine River Cruise'],
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Santorini',
    slug: 'santorini',
    country: 'Greece',
    region: 'Europe',
    description: 'Whitewashed cliffside villages, volcanic beaches, and legendary sunsets over the Aegean Sea.',
    shortDescription: 'Whitewashed villages and legendary Aegean sunsets.',
    images: [
      'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800&q=80',
    ],
    category: 'beach' as const,
    rating: 4.9,
    reviewCount: 156,
    packageCount: 18,
    startingPrice: 149999,
    bestSeason: 'May – Oct',
    visaType: 'required' as const,
    highlights: ['Oia Sunset', 'Caldera Views', 'Red Beach', 'Wine Tasting', 'Volcanic Hot Springs'],
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Nepal',
    slug: 'nepal',
    country: 'Nepal',
    region: 'South Asia',
    description: 'Home to the world\u2019s highest peaks — trek through the Himalayas, explore ancient temples, and experience raw adventure.',
    shortDescription: 'Himalayan treks, ancient temples, and raw adventure.',
    images: [
      'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80',
    ],
    category: 'adventure' as const,
    rating: 4.7,
    reviewCount: 134,
    packageCount: 16,
    startingPrice: 89999,
    bestSeason: 'Oct – May',
    visaType: 'on-arrival' as const,
    highlights: ['Everest Base Camp', 'Kathmandu Temples', 'Pokhara Lakes', 'Annapurna Circuit', 'Chitwan Safari'],
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Kenya Safari',
    slug: 'kenya-safari',
    country: 'Kenya',
    region: 'Africa',
    description: 'Witness the Great Migration, spot the Big Five, and sleep under the stars in the Maasai Mara — Africa\u2019s crown jewel.',
    shortDescription: 'Great Migration, Big Five, and Maasai Mara adventures.',
    images: [
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80',
    ],
    category: 'wildlife' as const,
    rating: 4.8,
    reviewCount: 98,
    packageCount: 12,
    startingPrice: 199999,
    bestSeason: 'Jul – Oct',
    visaType: 'required' as const,
    highlights: ['Maasai Mara', 'Big Five Safari', 'Great Migration', 'Hot Air Balloon', 'Amboseli National Park'],
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Kashmir',
    slug: 'kashmir',
    country: 'India',
    region: 'South Asia',
    description: 'Paradise on earth — snow-capped peaks, shikara rides on Dal Lake, saffron fields, and Mughal gardens in full bloom.',
    shortDescription: 'Snow-capped peaks, Dal Lake, and Mughal gardens.',
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    ],
    category: 'mountain' as const,
    rating: 4.7,
    reviewCount: 211,
    packageCount: 24,
    startingPrice: 54999,
    bestSeason: 'Apr – Oct',
    visaType: 'free' as const,
    highlights: ['Dal Lake Shikara', 'Gulmarg Gondola', 'Pahalgam Valley', 'Mughal Gardens', 'Saffron Fields'],
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'New York',
    slug: 'new-york',
    country: 'USA',
    region: 'North America',
    description: 'The city that never sleeps — Times Square, Central Park, world-class museums, and the iconic Manhattan skyline.',
    shortDescription: 'Times Square, Central Park, and the Manhattan skyline.',
    images: [
      'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80',
    ],
    category: 'city' as const,
    rating: 4.8,
    reviewCount: 167,
    packageCount: 15,
    startingPrice: 179999,
    bestSeason: 'Sep – Nov',
    visaType: 'required' as const,
    highlights: ['Times Square', 'Central Park', 'Statue of Liberty', 'Brooklyn Bridge', 'Broadway Shows'],
    isActive: true,
    isFeatured: false,
  },
];
