export const packagesSeed = [
  {
    name: 'Dubai Luxury Escape — Burj Khalifa & Desert Safari',
    slug: 'dubai-luxury-escape-burj-khalifa-and-desert-safari',
    destinationSlug: 'dubai',
    description: 'Experience the ultimate Dubai luxury getaway with stays at 5-star hotels, a thrilling desert safari, Burj Khalifa tickets, and a magical dhow cruise dinner under the stars.',
    images: [
      'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80',
    ],
    duration: { nights: 7, days: 8 },
    hotelRating: '5-Star',
    category: 'luxury' as const,
    originalPrice: 149999,
    price: 124999,
    discount: 17,
    rating: 4.9,
    reviewCount: 312,
    highlights: [
      'Burj Khalifa 124th floor access',
      'Premium desert safari with BBQ dinner',
      'Dhow cruise with live entertainment',
      'Dubai Mall & Aquarium visit',
    ],
    inclusions: [
      'Return flights',
      '5-star hotel accommodation',
      'Daily breakfast & select dinners',
      'Airport transfers',
      'Desert safari with BBQ',
      'Burj Khalifa tickets',
    ],
    exclusions: [
      'Travel insurance',
      'Personal expenses',
      'Meals not mentioned',
      'Visa fees',
      'Tips & gratuities',
    ],
    badge: 'Bestseller',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Dubai City & Dhow Cruise Getaway',
    slug: 'dubai-city-and-dhow-cruise-getaway',
    destinationSlug: 'dubai',
    description: 'Explore the best of Dubai city with a guided tour, shopping at Gold Souk, and a romantic dhow cruise dinner on Dubai Creek.',
    images: [
      'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80',
    ],
    duration: { nights: 5, days: 6 },
    hotelRating: '4-Star',
    category: 'luxury' as const,
    originalPrice: 109999,
    price: 89999,
    discount: 18,
    rating: 4.8,
    reviewCount: 219,
    highlights: [
      'Dubai city tour with guide',
      'Dhow cruise dinner on the Creek',
      'Gold Souk & Spice Souk visit',
      'Dubai Frame tickets',
    ],
    inclusions: [
      'Return flights',
      '4-star hotel accommodation',
      'Daily breakfast',
      'Airport transfers',
      'City tour',
      'Dhow cruise dinner',
    ],
    exclusions: [
      'Travel insurance',
      'Personal expenses',
      'Lunch & other meals',
      'Visa fees',
    ],
    badge: 'Hot Deal',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Singapore Classic with Universal Studios',
    slug: 'singapore-classic-with-universal-studios',
    destinationSlug: 'singapore',
    description: 'Discover Singapore\u2019s iconic attractions including Gardens by the Bay, Marina Bay Sands, Sentosa Island, and a full day at Universal Studios.',
    images: [
      'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80',
    ],
    duration: { nights: 5, days: 6 },
    hotelRating: '4-Star',
    category: 'family' as const,
    originalPrice: 89999,
    price: 72999,
    discount: 19,
    rating: 4.8,
    reviewCount: 401,
    highlights: [
      'Universal Studios full-day pass',
      'Gardens by the Bay with Supertree show',
      'Sentosa Island cable car',
      'Marina Bay Sands SkyPark',
    ],
    inclusions: [
      'Return flights',
      '4-star hotel accommodation',
      'Daily breakfast',
      'Airport transfers',
      'Universal Studios tickets',
      'Gardens by the Bay entry',
    ],
    exclusions: [
      'Travel insurance',
      'Personal expenses',
      'Meals not mentioned',
      'Optional tours',
      'Shopping expenses',
    ],
    badge: 'Popular',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Japan Cherry Blossom Season Special',
    slug: 'japan-cherry-blossom-season-special',
    destinationSlug: 'japan',
    description: 'Witness Japan\u2019s magical cherry blossom season with visits to Tokyo, Kyoto, Osaka, and Mount Fuji. Experience bullet trains, ancient temples, and modern marvels.',
    images: [
      'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80',
    ],
    duration: { nights: 9, days: 10 },
    hotelRating: '4-Star',
    category: 'luxury' as const,
    originalPrice: 139999,
    price: 114999,
    discount: 18,
    rating: 5.0,
    reviewCount: 178,
    highlights: [
      'Cherry blossom viewing at top spots',
      'Bullet train experience (Shinkansen)',
      'Mount Fuji day trip',
      'Kyoto temple tour with tea ceremony',
    ],
    inclusions: [
      'Return flights',
      '4-star hotel accommodation',
      'Daily breakfast',
      'Japan Rail Pass (7 days)',
      'Guided tours in Tokyo & Kyoto',
      'Mount Fuji excursion',
    ],
    exclusions: [
      'Travel insurance',
      'Personal expenses',
      'Meals not mentioned',
      'Visa fees',
      'Optional activities',
    ],
    badge: 'New',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Bali Honeymoon Private Villa Retreat',
    slug: 'bali-honeymoon-private-villa-retreat',
    destinationSlug: 'bali',
    description: 'A romantic Bali escape with private pool villas, couples spa treatments, sunset dinners, and visits to iconic temples and rice terraces.',
    images: [
      'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80',
    ],
    duration: { nights: 6, days: 7 },
    hotelRating: '5-Star',
    category: 'honeymoon' as const,
    originalPrice: 79999,
    price: 64999,
    discount: 19,
    rating: 4.9,
    reviewCount: 524,
    highlights: [
      'Private pool villa stay',
      'Couples spa & flower bath',
      'Ubud rice terrace tour',
      'Romantic sunset dinner',
    ],
    inclusions: [
      'Return flights',
      'Private pool villa accommodation',
      'Daily breakfast & 2 dinners',
      'Airport transfers',
      'Couples spa session',
      'Ubud & Tanah Lot tour',
    ],
    exclusions: [
      'Travel insurance',
      'Personal expenses',
      'Meals not mentioned',
      'Optional water sports',
    ],
    badge: 'Top Rated',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Bangkok & Phuket Beach Holiday',
    slug: 'bangkok-and-phuket-beach-holiday',
    destinationSlug: 'thailand',
    description: 'The perfect Thailand combo — explore Bangkok\u2019s temples and street food, then unwind on Phuket\u2019s stunning beaches with island-hopping adventures.',
    images: [
      'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&q=80',
    ],
    duration: { nights: 6, days: 7 },
    hotelRating: '4-Star',
    category: 'adventure' as const,
    originalPrice: 69999,
    price: 54999,
    discount: 21,
    rating: 4.8,
    reviewCount: 374,
    highlights: [
      'Grand Palace & Wat Pho visit',
      'Phi Phi Island day trip',
      'Bangkok floating market tour',
      'Phuket beach relaxation',
    ],
    inclusions: [
      'Return flights',
      '4-star hotel accommodation',
      'Daily breakfast',
      'Airport & inter-city transfers',
      'Bangkok city tour',
      'Phi Phi Island trip',
    ],
    exclusions: [
      'Travel insurance',
      'Personal expenses',
      'Meals not mentioned',
      'Optional nightlife tours',
      'Water sports',
    ],
    badge: 'Bestseller',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Maldives Overwater Bungalow Experience',
    slug: 'maldives-overwater-bungalow-experience',
    destinationSlug: 'maldives',
    description: 'Live the dream in an overwater bungalow with glass floors, private decks, all-inclusive dining, and world-class snorkeling in crystal-clear waters.',
    images: [
      'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80',
    ],
    duration: { nights: 5, days: 6 },
    hotelRating: '5-Star',
    category: 'luxury' as const,
    originalPrice: 149999,
    price: 119999,
    discount: 20,
    rating: 5.0,
    reviewCount: 209,
    highlights: [
      'Overwater bungalow with glass floor',
      'All-inclusive meals & drinks',
      'Sunset dolphin cruise',
      'Snorkeling & water sports',
    ],
    inclusions: [
      'Return flights',
      'Overwater bungalow accommodation',
      'All-inclusive meals & beverages',
      'Speedboat airport transfers',
      'Snorkeling equipment',
      'Sunset dolphin cruise',
    ],
    exclusions: [
      'Travel insurance',
      'Premium spa treatments',
      'Scuba diving courses',
      'Personal shopping',
    ],
    badge: 'All-Inclusive',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Singapore + Sentosa Island Luxury Package',
    slug: 'singapore-sentosa-island-luxury-package',
    destinationSlug: 'singapore',
    description: 'A premium Singapore experience combining city highlights with Sentosa Island luxury — includes S.E.A. Aquarium, cable car rides, and a stay at a 5-star resort.',
    images: [
      'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80',
    ],
    duration: { nights: 6, days: 7 },
    hotelRating: '5-Star',
    category: 'luxury' as const,
    originalPrice: 129999,
    price: 105000,
    discount: 19,
    rating: 4.9,
    reviewCount: 188,
    highlights: [
      '5-star Sentosa resort stay',
      'S.E.A. Aquarium visit',
      'Cable car ride with views',
      'Night Safari experience',
    ],
    inclusions: [
      'Return flights',
      '5-star resort accommodation',
      'Daily breakfast & 1 dinner',
      'Airport transfers',
      'S.E.A. Aquarium tickets',
      'Night Safari entry',
    ],
    exclusions: [
      'Travel insurance',
      'Personal expenses',
      'Meals not mentioned',
      'Optional tours',
      'Shopping expenses',
    ],
    badge: 'Premium',
    isActive: true,
    isFeatured: true,
  },
];
