export const reviewsSeed = [
  {
    rating: 5,
    title: "Absolutely magical honeymoon!",
    text: "LetsLive Tours made our honeymoon to Dubai absolutely magical. Every detail was perfectly planned — from the private villa to the sunset dinner cruise. The desert safari was the highlight — dune bashing at sunset followed by a BBQ under the stars was something we'll never forget.",
    tripType: "honeymoon",
    isVerified: true,
    isApproved: true,
    packageSlug: "dubai-luxury-escape-burj-khalifa-desert-safari",
    userName: "Priya Sharma",
  },
  {
    rating: 5,
    title: "Dubai family trip was flawless!",
    text: "Travelled with my family of 4 including two kids. The team at LetsLive was incredibly helpful in customising the itinerary for us. The Burj Khalifa experience was breathtaking — my kids were speechless! The guide on the heritage tour was knowledgeable and engaging. Will definitely book again.",
    tripType: "family",
    isVerified: true,
    isApproved: true,
    packageSlug: "dubai-luxury-escape-burj-khalifa-desert-safari",
    userName: "Rajesh Mehta",
  },
  {
    rating: 5,
    title: "Japan in blossom season was a dream",
    text: "Japan in cherry blossom season was a dream come true. Mt Fuji at sunrise, food tours in Tokyo, the ancient temples of Kyoto — all curated to perfection. LetsLive's attention to detail is unmatched. The bullet train experience alone was worth the trip. Truly world-class service.",
    tripType: "solo",
    isVerified: true,
    isApproved: true,
    packageSlug: "japan-cherry-blossom-season-special",
    userName: "Ananya Nair",
  },
  {
    rating: 5,
    title: "Maldives exceeded every expectation",
    text: "The Maldives overwater bungalow experience exceeded every expectation. Waking up to crystal-clear waters, snorkeling right from our deck, and the private sunset dinner on the beach — utter paradise. LetsLive handled everything seamlessly from flights to transfers.",
    tripType: "honeymoon",
    isVerified: true,
    isApproved: true,
    packageSlug: "maldives-overwater-bungalow-experience",
    userName: "Siddharth Rao",
  },
  {
    rating: 5,
    title: "Singapore + Sentosa was incredible!",
    text: "Singapore + Sentosa was incredible. Universal Studios, the Night Safari, Gardens by the Bay — we packed so much into 6 days without feeling rushed. The hotel was perfectly located and the transfers were always on time. Will book again for sure!",
    tripType: "family",
    isVerified: true,
    isApproved: true,
    packageSlug: "singapore-classic-with-universal-studios",
    userName: "Kavita Menon",
  },
  {
    rating: 5,
    title: "Phuket beaches were breathtaking",
    text: "Phuket beaches were breathtaking. The island-hopping tour to Phi Phi Islands was the best day of my life. Crystal clear waters, limestone cliffs, and the most amazing Thai food. LetsLive's local guide knew all the hidden spots. Best trip of my life!",
    tripType: "group",
    isVerified: true,
    isApproved: true,
    packageSlug: "bangkok-phuket-beach-holiday",
    userName: "Arjun Kapoor",
  },
  {
    rating: 4,
    title: "Great Bali experience with minor hiccups",
    text: "Overall a fantastic Bali honeymoon. The private villa was stunning, the rice terrace trek was memorable, and the spa treatments were heavenly. Only minor issue — one transfer was 20 minutes late. But the team resolved it quickly and even upgraded our dinner reservation as compensation.",
    tripType: "honeymoon",
    isVerified: true,
    isApproved: true,
    packageSlug: "bali-honeymoon-private-villa-retreat",
    userName: "Neha Gupta",
  },
  {
    rating: 5,
    title: "Dubai City & Dhow Cruise — perfect short trip",
    text: "Perfect 5-night getaway. The Dhow Cruise dinner was romantic and the city tour covered all the highlights efficiently. Our guide was knowledgeable and funny. The hotel was excellent value for money. Highly recommend for a quick Dubai escape.",
    tripType: "solo",
    isVerified: true,
    isApproved: true,
    packageSlug: "dubai-city-dhow-cruise-getaway",
    userName: "Vikram Singh",
  },
  {
    rating: 5,
    title: "Sentosa Island luxury was worth every penny",
    text: "The Singapore + Sentosa luxury package was worth every penny. The Resorts World Sentosa stay was phenomenal, the private yacht tour around the islands was unforgettable, and the food — oh the food! From hawker centres to Michelin-starred restaurants, Singapore delivered.",
    tripType: "honeymoon",
    isVerified: true,
    isApproved: true,
    packageSlug: "singapore-sentosa-island-luxury-package",
    userName: "Deepika Patel",
  },
  {
    rating: 4,
    title: "Solid Japan package, could use more free time",
    text: "The Japan Cherry Blossom package was well-organized and the timing was perfect — we caught peak bloom in Kyoto. The bullet train experience was smooth. My only feedback: the itinerary was slightly packed. Would have loved one more free day to explore Tokyo on our own.",
    tripType: "group",
    isVerified: true,
    isApproved: true,
    packageSlug: "japan-cherry-blossom-season-special",
    userName: "Rohan Desai",
  },
];
